CREATE TABLE TB_DEPARTMENT(
    DEPARTMENT_NO VARCHAR2(10) CONSTRAINT DEPT_NO_PK PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(20) NOT NULL,
    CATEGORY VARCHAR2(20),
    OPEN_YN CHAR(1),
    CAPACITY NUMBER
);
COMMENT ON COLUMN TB_DEPARTMENT.DEPARTMENT_NO IS '학과 번호';
COMMENT ON COLUMN TB_DEPARTMENT.DEPARTMENT_NAME IS '학과 이름';
COMMENT ON COLUMN TB_DEPARTMENT.CATEGORY IS '계열';
COMMENT ON COLUMN TB_DEPARTMENT.OPEN_YN IS '개설 여부';
COMMENT ON COLUMN TB_DEPARTMENT.CAPACITY IS '정원';


CREATE TABLE TB_STUDENT(
    STUDENT_NO VARCHAR2(10) CONSTRAINT STUD_NO_PK PRIMARY KEY,
    DEPARTMENT_NO VARCHAR2(10) NOT NULL,
    STUDENT_NAME VARCHAR2(30) NOT NULL,
    STUDENT_SSN VARCHAR2(14),
    STUDENT_ADDRESS VARCHAR2(100),
    ENTRANCE_DATE DATE,
    ABSENCE_YN CHAR(1),
    COACH_PROFESSOR_NO VARCHAR2(10)
);
COMMENT ON COLUMN TB_STUDENT.STUDENT_NO IS '학생 번호';
COMMENT ON COLUMN TB_STUDENT.DEPARTMENT_NO IS '학과 번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_NAME IS '학생 이름';
COMMENT ON COLUMN TB_STUDENT.STUDENT_SSN IS '학생 주민번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_ADDRESS IS '학생 주소';
COMMENT ON COLUMN TB_STUDENT.ENTRANCE_DATE IS '입학 일자';
COMMENT ON COLUMN TB_STUDENT.ABSENCE_YN IS '휴학 여부';
COMMENT ON COLUMN TB_STUDENT.COACH_PROFESSOR_NO IS '지도 교수 번호';

ALTER TABLE TB_STUDENT
ADD CONSTRAINT DEPT_NO_FK FOREIGN KEY(DEPARTMENT_NO) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO);
ALTER TABLE TB_STUDENT
ADD CONSTRAINT COACH_PROF_NO_FK FOREIGN KEY(COACH_PROFESSOR_NO) REFERENCES TB_PROFESSOR(PROFESSOR_NO);


CREATE TABLE TB_CLASS(
    CLASS_NO VARCHAR2(10) CONSTRAINT CLASS_NO_PK PRIMARY KEY,
    DEPARTMENT_NO VARCHAR2(10) NOT NULL,
    PREATTENDING_CLASS_NO VARCHAR2(10),
    CLASS_NAME VARCHAR2(30) NOT NULL,
    CLASS_TYPE VARCHAR2(10)
);
COMMENT ON COLUMN TB_CLASS.CLASS_NO IS '과목 번호';
COMMENT ON COLUMN TB_CLASS.DEPARTMENT_NO IS '학과 번호';
COMMENT ON COLUMN TB_CLASS.PREATTENDING_CLASS_NO IS '선수 과목 번호';
COMMENT ON COLUMN TB_CLASS.CLASS_NAME IS '과목 이름';
COMMENT ON COLUMN TB_CLASS.CLASS_TYPE IS '과목 구분';

ALTER TABLE TB_CLASS
ADD CONSTRAINT CL_DEPT_NO_FK FOREIGN KEY(DEPARTMENT_NO) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO);
ALTER TABLE TB_CLASS
--PREATTENDING_CLASS_NO FK설정하기..


CREATE TABLE TB_CLASS_PROFESSOR(
    CLASS_NO VARCHAR2(10),
    PROFESSOR_NO VARCHAR2(10),
    CONSTRAINT CLASS_PROF_NO_PK PRIMARY KEY(CLASS_NO,PROFESSOR_NO)
);
COMMENT ON COLUMN TB_CLASS_PROFESSOR.CLASS_NO IS '과목 번호';
COMMENT ON COLUMN TB_CLASS_PROFESSOR.PROFESSOR_NO IS '교수 번호';

ALTER TABLE TB_CLASS_PROFESSOR
ADD CONSTRAINT CLASS_NO_FK FOREIGN KEY(CLASS_NO) REFERENCES TB_CLASS(CLASS_NO);
ALTER TABLE TB_CLASS_PROFESSOR
ADD CONSTRAINT PROF_NO_FK FOREIGN KEY(PROFESSOR_NO) REFERENCES TB_PROFESSOR(PROFESSOR_NO);


CREATE TABLE TB_PROFESSOR(
    PROFESSOR_NO VARCHAR2(10) CONSTRAINT PROF_NO_PK PRIMARY KEY,
    PROFESSOR_NAME VARCHAR2(30) NOT NULL,
    PROFESSOR_SSN VARCHAR2(14),
    PROFESSOR_ADDRESS VARCHAR2(100),
    DEPARTMENT_NO VARCHAR2(10)
);
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_NO IS '교수 번호';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_NAME IS '교수 이름';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_SSN IS '교수 주민번호';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_ADDRESS IS '교수 주소';
COMMENT ON COLUMN TB_PROFESSOR.DEPARTMENT_NO IS '학과 번호';

ALTER TABLE TB_PROFESSOR
ADD CONSTRAINT PRO_DEPT_NO_FK FOREIGN KEY(DEPARTMENT_NO) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO);


CREATE TABLE TB_GRADE(
    TERM_NO VARCHAR2(10),
    CLASS_NO VARCHAR2(10),
    STUDENT_NO VARCHAR2(10),
    POINT NUMBER(3,2),
    CONSTRAINT TERM_CLASS_STUD_NO_PK PRIMARY KEY (TERM_NO, CLASS_NO, STUDENT_NO)
);
COMMENT ON COLUMN TB_GRADE.TERM_NO IS '학기 번호';
COMMENT ON COLUMN TB_GRADE.CLASS_NO IS '과목 번호';
COMMENT ON COLUMN TB_GRADE.STUDENT_NO IS '학생 번호';
COMMENT ON COLUMN TB_GRADE.POINT IS '학점';

ALTER TABLE TB_GRADE
ADD CONSTRAINT GR_CLASS_NO_FK FOREIGN KEY(CLASS_NO) REFERENCES TB_CLASS(CLASS_NO);
ALTER TABLE TB_GRADE
ADD CONSTRAINT STUDENT_NO_FK FOREIGN KEY(STUDENT_NO) REFERENCES TB_STUDENT(STUDENT_NO);
