CREATE TABLE STUDENT_TBL(
    STUDENT_ID VARCHAR2(15),
    STUDENT_PWD VARCHAR2(15),
    STUDENT_NAME VARCHAR2(20),
    GENDER CHAR(1),
    AGE NUMBER,
    EMAIL VARCHAR2(30),
    PHONE CHAR(11),
    ADDRESS VARCHAR2(500),
    HOBBY VARCHAR2(50),
    ENROLL_DATE DATE DEFAULT SYSDATE
);
DROP TABLE STUDENT_TBL;

ALTER TABLE STUDENT_TBL
ADD CONSTRAINT STUDENT_PK PRIMARY KEY (STUDENT_ID);
ALTER TABLE STUDENT_TBL
MODIFY STUDENT_PWD NOT NULL;
ALTER TABLE STUDENT_TBL
MODIFY STUDENT_NAME NOT NULL;
ALTER TABLE STUDENT_TBL
MODIFY AGE NOT NULL;
ALTER TABLE STUDENT_TBL
ADD CHECK(GENDER IN('M','F'));

SELECT * FROM USER_CONSTRAINTS;

INSERT INTO STUDENT_TBL
VALUES('admin', 'admin', '관리자', 'M', 30, 'admin@iei.or.kr', '01012345678', '서울시 강남구 역삼동 테헤란로 7', '기타, 독서, 운동', DEFAULT);

SELECT * FROM STUDENT_TBL;
DELETE FROM STUDENT_TBL;
COMMIT; -- 커밋을 해야만 이클립스에서 보인다.

INSERT INTO STUDENT_TBL
VALUES('user11', 'user11', '홍길동', 'M', 23, 'hong77@kh.org', '01077778888', '경기도 수원시 팔달구 팔달동 77', '기타, 등산, 운동', DEFAULT);
COMMIT;

DELETE FROM STUDENT_TBL
WHERE STUDENT_ID = 'user03';