CREATE TABLE DEPARTMENT(
    DEPT_ID CHAR(2),
    DEPT_TITLE VARCHAR(35),
    LOCATION_ID CHAR(2)
);
INSERT INTO DEPARTMENT
VALUES('D1', '인사관리부', 'L1');
INSERT INTO DEPARTMENT
VALUES('D2', '회계관리부', 'L1');
INSERT INTO DEPARTMENT
VALUES('D3', '마케팅부', 'L1');
INSERT INTO DEPARTMENT
VALUES('D4', '국내영업부', 'L1');
INSERT INTO DEPARTMENT
VALUES('D5', '해외영업1부', 'L2');
INSERT INTO DEPARTMENT
VALUES('D6', '해외영업2부', 'L3');
INSERT INTO DEPARTMENT
VALUES('D7', '해외영업3부', 'L4');
INSERT INTO DEPARTMENT
VALUES('D8', '기술지원부', 'L5');
INSERT INTO DEPARTMENT
VALUES('D9', '총무부', 'L1');

CREATE TABLE EMPLOYEE(
    EMP_ID VARCHAR2(3),
    EMP_NAME VARCHAR2(20),
    EMP_NO CHAR(14),
    EMAIL VARCHAR2(25),
    PHONE VARCHAR2(12),
    DEPT_CODE CHAR(2),
    JOB_CODE CHAR(2),
    SAL_LEVEL CHAR(2),
    SALARY NUMBER,
    BONUS NUMBER,
    MANAGER_ID VARCHAR(3),
    HIRE_DATE DATE,
    ENT_DATE DATE,
    ENT_YN CHAR(1)
);

CREATE TABLE JOB(
    JOB_CODE CHAR(2),
    JOB_NAME VARCHAR(35)
);

INSERT INTO JOB
VALUES('J1', '대표');
INSERT INTO JOB
VALUES('J2', '부사장');
INSERT INTO JOB
VALUES('J3', '부장');
INSERT INTO JOB
VALUES('J4', '차장');
INSERT INTO JOB
VALUES('J5', '과장');
INSERT INTO JOB
VALUES('J6', '대리');
INSERT INTO JOB
VALUES('J7', '사원');