--UNIQUE 제약조건
INSERT INTO JOB
VALUES(NULL, '주임');


--NOT NULL제약조건
INSERT INTO DEPARTMENT
VALUES(NULL, NULL, 'L1');


--NULL이 들어가지 않고 중복도 되지 않도록 하는 제약조건
--고유식별자로써의 역할을 하도록함.
CREATE TABLE JOB(
    JOB_CODE CHAR(2) CONSTRAINT JOB_PK PRIMARY KEY,
    JOB_NAME VARCHAR2(35)
);
DROP TABLE JOB;

CREATE TABLE DEPARTMENT(
    DEPT_ID CHAR(2) NOT NULL,
    DEPT_TITLE VARCHAR2(35),
    LOCATION_ID CHAR(2) NOT NULL
);
DROP TABLE DEPARTMENT;
--제약조건삭제
ALTER TABLE DEPARTMENT
DROP CONSTRAINT SYS_C007003;

--제약조건추가
ALTER TABLE DEPARTMENT
ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY(DEPT_ID);

--제약조건이름 수정
ALTER TABLE DEPARTMENT
RENAME CONSTRAINT DEPARTMENT_PK TO DEPT_ID_PK;

COMMENT ON COLUMN DEPARTMENT.DEPT_ID IS '부서코드';
COMMENT ON COLUMN DEPARTMENT.DEPT_TITLE IS '부서명';
COMMENT ON COLUMN DEPARTMENT.LOCATION_ID IS '지역코드';

DESC DEPARTMENT;

ALTER TABLE DEPARTMENT
RENAME COLUMN DEPT_ID TO DEPT_CODE;

ALTER TABLE DEPARTMENT
RENAME TO APE;

ALTER TABLE APE
RENAME TO DEPARTMENT;

--컬럼 데이터타입 수정
ALTER TABLE DEPARTMENT
MODIFY DEPT_TITLE VARCHAR2(40);

--컬럼추가
ALTER TABLE DEPARTMENT
ADD(DEPT_NAME VARCHAR2(30));

--컬럼 삭제
ALTER TABLE DEPARTMENT
DROP COLUMN DEPT_NAME;

--제약조건 확인
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'DEPARTMENT';
--**CONSTRAINT TYPE
--P : PRIMARY KEY
--R : FOREIGN KEY
--C : CHECK OR NOT NULL
--U : UNIQUE

--혼자 바꿔보기
COMMENT ON COLUMN EMPLOYEE.EMP_ID IS '사원번호';
COMMENT ON COLUMN EMPLOYEE.EMP_NAME IS '직원명';
COMMENT ON COLUMN EMPLOYEE.EMP_NO IS '주민등록번호';
COMMENT ON COLUMN EMPLOYEE.EMAIL IS '이메일';
COMMENT ON COLUMN EMPLOYEE.PHONE IS '전화번호';
COMMENT ON COLUMN EMPLOYEE.DEPT_CODE IS '부서코드';
COMMENT ON COLUMN EMPLOYEE.JOB_CODE IS '직급코드';
COMMENT ON COLUMN EMPLOYEE.SAL_LEVEL IS '급여등급';
COMMENT ON COLUMN EMPLOYEE.SALARY IS '급여';
COMMENT ON COLUMN EMPLOYEE.BONUS IS '보너스율';
COMMENT ON COLUMN EMPLOYEE.MANAGER_ID IS '관리자사번';
COMMENT ON COLUMN EMPLOYEE.HIRE_DATE IS '입사일';
COMMENT ON COLUMN EMPLOYEE.ENT_DATE IS '퇴사일';
COMMENT ON COLUMN EMPLOYEE.ENT_YN IS '재직여부';

ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY(EMP_ID);
ALTER TABLE EMPLOYEE
MODIFY EMP_NAME NOT NULL
MODIFY EMP_NO NOT NULL
MODIFY JOB_CODE NOT NULL
MODIFY SAL_LEVEL NOT NULL;

COMMENT ON COLUMN JOB.JOB_CODE IS '직급코드';
COMMENT ON COLUMN JOB.JOB_NAME IS '직급명';

COMMENT ON COLUMN LOCATION.LOCAL_CODE IS '지역코드';
COMMENT ON COLUMN LOCATION.NATIONAL_CODE IS '국가코드';
COMMENT ON COLUMN LOCATION.LOCAL_NAME IS '지역명';

ALTER TABLE LOCATION
MODIFY LOCAL_CODE NOT NULL
MODIFY NATIONAL_CODE NOT NULL;

COMMENT ON COLUMN NATIONAL.NATIONAL_CODE IS '국가코드';
COMMENT ON COLUMN NATIONAL.NATIONAL_NAME IS '국가명';

ALTER TABLE NATIONAL
MODIFY NATIONAL_CODE NOT NULL;

COMMENT ON COLUMN SAL_GRADE.SAL_LEVEL IS '급여등급';
COMMENT ON COLUMN SAL_GRADE.MIN_SAL IS '최소급여';
COMMENT ON COLUMN SAL_GRADE.MAX_SAL IS '최대급여';

ALTER TABLE SAL_GRADE
MODIFY SAL_LEVEL NOT NULL;