

CREATE TABLE STUDENT_TBL(
    STUDENT_NAME VARCHAR2(20),
    STUDENT_AGE NUMBER,
    STUDENT_GRADE NUMBER,
    STUDENT_ADDRESS VARCHAR2(100)
);
--수정 -> 삭제 + 생성
--테이블 삭제
DROP TABLE STUDENT_TBL;

--TABLE에 데이터를 넣는 방법! -> 회원가입
INSERT INTO STUDENT_TBL(STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS)
VALUES('일용자', 22, 1, '서울');
--컬럼명 생략 가능!
INSERT INTO STUDENT_TBL
VALUES('이용자', 23, 2, '서울시 종로구');

INSERT INTO STUDENT_TBL
VALUES(NULL, 33, 3, NULL);

INSERT INTO STUDENT_TBL
VALUES(' ', 55, 5, NULL);
--데이터를 삭제해보자 -> 회원탈퇴
DELETE FROM STUDENT_TBL;

INSERT INTO STUDENT_TBL
VALUES('일용자', 11, 1, '서울시 중구');
INSERT INTO STUDENT_TBL
VALUES('이용자', 22, 2, '서울시 종로구');
INSERT INTO STUDENT_TBL
VALUES('삼용자', 33, 3, '서울시 동대문구');
INSERT INTO STUDENT_TBL
VALUES('사용자', 44, 4, '서울시 서대문구');

--특정한 행을 지정하고 바꿀값이 있는 테이블, 바꿀값을 넣어준다.
UPDATE STUDENT_TBL
SET STUDENT_AGE = 99
WHERE STUDENT_GRADE = 2;

DELETE FROM STUDENT_TBL
WHERE STUDENT_GRADE = 2;

CREATE TABLE DATATYPE_TBL(
    MOONJJA CHAR(10),   
    --알파벳 10글자, 한글3글자
    MOONJJAYUL VARCHAR2(100), 
    --알파벳 100글자, 한글33글자
    SOOJJA NUMBER,
    NALJJA DATE,
    NALJJA2 TIMESTAMP
);

DESC DATATYPE_TBL;
INSERT INTO DATATYPE_TBL
VALUES('문자', '문자열', 22, SYSDATE, SYSTIMESTAMP);

SELECT MOONJJA, MOONJJAYUL, SOOJJA, NALJJA, NALJJA2
FROM DATATYPE_TBL;

INSERT INTO DATATYPE_TBL
VALUES('문자2', '문자열2', 33, SYSDATE, SYSTIMESTAMP);

UPDATE DATATYPE_TBL
SET MOONJJA = '오라클'
WHERE SOOJJA = 33;

DELETE FROM DATATYPE_TBL
WHERE SOOJJA = 22;
--데이터 조회(FROM -> WHERE -> SELECT)
SELECT STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS
FROM STUDENT_TBL
WHERE STUDENT_GRADE = 2;