--사용자 계정 생성, 권한부여 및 해제
CREATE USER STUDENT IDENTIFIED BY STUDENT;

GRANT CONNECT TO STUDENT;

GRANT RESOURCE TO STUDENT;

CREATE TABLE STUDENT_TBL(
    STUDENT_NAME VARCHAR(20),
    STUDENT_AGE NUMBER,
    STUDENT_GRADE NUMBER,
    STUDENT_ADDRESS VARCHAR(100)
);
--KH계정을 만들고 그 비밀번호는 KH로 해주세요.
CREATE USER KH IDENTIFIED BY KH;
--접속이 가능하고 테이블이 생성이 되도록 해주세요.
GRANT CONNECT, RESOURCE TO KH;
--접속이름을 만들어 접속해보세요!